### ISSUE TITLE
EPACTS make-kin

### ISSUE THREAD

**Issue by ana-stankovic** [statgen/EPACTS#23]
I am using EPACTS v3.4.2 and I am trying to run Single Variant Test - q.emmax test. I am using the provided test files.
I am generating the kinship matrix with the` epacts make-kin` function. 
This is the command line:
`epacts make-kin --vcf 1000G_exome_chr20_example_softFiltered.calls.anno.vcf.gz --out 37_342.kinf --ped 1000G_dummy_pheno.ped --run 1 --ref human_g1k_v37.fasta`

I use this file in the emmax test:
`epacts single --vcf /1000G_exome_chr20_example_softFiltered.calls.anno.vcf.gz --ped /1000G_dummy_pheno.ped --out emmax.q.emmax --test q.emmax --pheno DISEASE  --cov AGE --cov SEX --run 8 --ref /human_g1k_v37_decoy.fasta --kinf /37_342.kinf`

The task fails with the following error log: 
[job.err-4.log](https://github.com/statgen/EPACTS/files/4730982/job.err-4.log)

But, when I use the kinship file created by all  the same files and the same command line, but using EPACTS v3.3.0, the Single Variant test (v3.4.2) passes without errors.

Do you have some insights into what could be the reason behind this?
Thank you!

**Comment by jonathonl** [comment]
I'm pretty sure this should be fixed with 0321c8c8bea1c5ba9daf1beeedd09cffdf9f19fe, which is not in the latest RC.

**Comment by ana-stankovic** [comment]
I have applied the changes from this commit, unfortunately it is still not working. 
I created a new kinship file and ran the same variant test, and I still get the following error in the log: [err37.log](https://github.com/statgen/EPACTS/files/4732968/err37.log)

Is the change in this file the only one needed, or are there commits before this that I maybe need as well?

**Comment by jonathonl** [comment]
it would be safest to either checkout that commit or checkout the latest commit from the develop branch. You will also need to delete the output from the previous run (specifically the kinship file) since EPACTS will not recreate the file if it already exists.

**Comment by jonathonl** [comment]
I reread your comment and see that you did delete the kinship file. Am I correct in assuming that you did a rebuild and reinstall after pulling in the change?

**Comment by jonathonl** [comment]
FYI, I just successfully ran these commands using the latest from develop and the 1000g reference file you are using. I don't have permission to view the Dockerfile you linked in the other thread, so I'm unable to test with your exact environment.

**Comment by ana-stankovic** [comment]
Hello, I just wanted to say that we have successfully ran the EMMAX test with the new kinship file built with the development branch.
Thank you for the help!

**Comment by freedomq8** [comment]
Hello, i have the same error, however i am using the docker image due to epacts plots errors. is it possible to update the bug fix to the docker image ?

Thanks

**Comment by zhangchuyi** [comment]
> Hello, I just wanted to say that we have successfully ran the EMMAX test with the new kinship file built with the development branch. Thank you for the help!

Hello, I met the exact same type of error as yours, could you please tell how did you fix it ? Thanks in advance!
